version: '2'
services:
  db:
    cap_add:
    - SYS_PTRACE
    environment:
    - MSSQL_SA_PASSWORD=yourStrong(!)Password
    - ACCEPT_EULA=1
    ports:
    - "1433:1433"
    user:
      root
    build:
      context: .
      dockerfile: ./DockerfileDb
  populator:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
    - db
    depends_on:
    - db

